src/Entity/Bulletin.php
<?php

namespace App\Entity;

use App\Repository\BulletinRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BulletinRepository::class)
 */
class Bulletin
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    /**
     * @ORM\Column(type="float",options={"default" : 0})
     */
    private $TotalHeureSupp;

    /**
     * @ORM\Column(type="float",options={"default" : 0})
     */
    private $TotalHeureAbs;

    /**
     * @ORM\Column(type="float")
     */
    private $IEP;

    /**
     * @ORM\Column(type="float")
     */
    private $allocationFamiliale;

    /**
     * @ORM\Column(type="float",options={"default" : 0})
     */
    private $panier;

    /**
     * @ORM\Column(type="float",options={"default" : 0})
     */
    private $cotisations;

    /**
     * @ORM\Column(type="float",options={"default" : 0})
     */
    private $impots;

    /**
     * @ORM\Column(type="float")
     */
    private $Total;

    /**
     * @ORM\ManyToOne(targetEntity=Employe::class, inversedBy="bulletin")
     * @ORM\JoinColumn(nullable=false)
     */
    private $employe;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getTotalHeureSupp(): ?float
    {
        return $this->TotalHeureSupp;
    }

    public function setTotalHeureSupp(float $TotalHeureSupp): self
    {
        $this->TotalHeureSupp = $TotalHeureSupp;

        return $this;
    }

    public function getTotalHeureAbs(): ?float
    {
        return $this->TotalHeureAbs;
    }

    public function setTotalHeureAbs(float $TotalHeureAbs): self
    {
        $this->TotalHeureAbs = $TotalHeureAbs;

        return $this;
    }

    public function getIEP(): ?float
    {
        return $this->IEP;
    }

    public function setIEP(float $IEP): self
    {
        $this->IEP = $IEP;

        return $this;
    }

    public function getAllocationFamiliale(): ?float
    {
        return $this->allocationFamiliale;
    }

    public function setAllocationFamiliale(float $allocationFamiliale): self
    {
        $this->allocationFamiliale = $allocationFamiliale;

        return $this;
    }

    public function getPanier(): ?float
    {
        return $this->panier;
    }

    public function setPanier(float $panier): self
    {
        $this->panier = $panier;

        return $this;
    }

    public function getCotisations(): ?float
    {
        return $this->cotisations;
    }

    public function setCotisations(float $cotisations): self
    {
        $this->cotisations = $cotisations;

        return $this;
    }

    public function getImpots(): ?float
    {
        return $this->impots;
    }

    public function setImpots(float $impots): self
    {
        $this->impots = $impots;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->Total;
    }

    public function setTotal(float $Total): self
    {
        $this->Total = $Total;

        return $this;
    }

    public function getEmploye(): ?Employe
    {
        return $this->employe;
    }

    public function setEmploye(?Employe $employe): self
    {
        $this->employe = $employe;

        return $this;
    }
}

src/Entity/Employe.php
<?php

namespace App\Entity;

use App\Repository\EmployeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * Class Employe
 * @package App\Entity
 * @ORM\MappedSuperclass
 * @ORM\Entity(repositoryClass=EmployeRepository::class)
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({"employe" = "Employe","rh"="Rh","directeurgeneral"="DirecteurGeneral","comptable"="Comptable","directeur"="Directeur"})
 */
class Employe extends User
{
    /**
     * @ORM\Column(type="string", length=50)
     */
    protected $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    protected $prenom;

    /**
     * @ORM\Column(type="date_immutable")
     */
    protected $dateNaissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $lieuNaissance;

    /**
     * @ORM\Column(type="string", length=10)
     */
    protected $sexe;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $numeroTelephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $ccp;

    /**
     * @ORM\Column(type="string", length=20)
     */
   protected $SituationFamiliale;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    protected $nombreEnfant;

    /**
     * @ORM\Column(type="date_immutable")
     */
    protected $dateRecrutement;


    /**
     * @ORM\ManyToOne(targetEntity=Filiale::class, inversedBy="employes")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $filiale;

    /**
     * @ORM\OneToMany(targetEntity=Bulletin::class, mappedBy="employe")
     */
   protected $bulletin;

    /**
     * @ORM\OneToMany(targetEntity=Presence::class, mappedBy="employe", orphanRemoval=true)
     */
   protected $presence;

    /**
     * @ORM\ManyToOne(targetEntity=Poste::class, inversedBy="employes")
     * @ORM\JoinColumn(nullable=false)
     */
   protected $poste;

    public function __construct()
    {
        $this->bulletin = new ArrayCollection();
        $this->presence = new ArrayCollection();
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeImmutable
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeImmutable $dateNaissance): self
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getLieuNaissance(): ?string
    {
        return $this->lieuNaissance;
    }

    public function setLieuNaissance(string $lieuNaissance): self
    {
        $this->lieuNaissance = $lieuNaissance;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getNumeroTelephone(): ?string
    {
        return $this->numeroTelephone;
    }

    public function setNumeroTelephone(string $numeroTelephone): self
    {
        $this->numeroTelephone = $numeroTelephone;

        return $this;
    }

    public function getCcp(): ?string
    {
        return $this->ccp;
    }

    public function setCcp(string $ccp): self
    {
        $this->ccp = $ccp;

        return $this;
    }

    public function getSituationFamiliale(): ?string
    {
        return $this->SituationFamiliale;
    }

    public function setSituationFamiliale(string $SituationFamiliale): self
    {
        $this->SituationFamiliale = $SituationFamiliale;

        return $this;
    }

    public function getNombreEnfant(): ?int
    {
        return $this->nombreEnfant;
    }

    public function setNombreEnfant(?int $nombreEnfant): self
    {
        $this->nombreEnfant = $nombreEnfant;

        return $this;
    }
    public function getDateRecrutement(): ?\DateTimeImmutable
    {
        return $this->dateRecrutement;
    }

    public function setDateRecrutement(\DateTimeImmutable $dateRecrutement): self
    {
        $this->dateRecrutement = $dateRecrutement;

        return $this;
    }

    public function getFiliale(): ?Filiale
    {
        return $this->filiale;
    }

    public function setFiliale(?Filiale $filiale): self
    {
        $this->filiale = $filiale;

        return $this;
    }

    /**
     * @return Collection|Bulletin[]
     */
    public function getBulletin(): Collection
    {
        return $this->bulletin;
    }

    public function addBulletin(Bulletin $bulletin): self
    {
        if (!$this->bulletin->contains($bulletin)) {
            $this->bulletin[] = $bulletin;
            $bulletin->setEmploye($this);
        }

        return $this;
    }

    public function removeBulletin(Bulletin $bulletin): self
    {
        if ($this->bulletin->removeElement($bulletin)) {
            // set the owning side to null (unless already changed)
            if ($bulletin->getEmploye() === $this) {
                $bulletin->setEmploye(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Presence[]
     */
    public function getPresence(): Collection
    {
        return $this->presence;
    }

    public function addPresence(Presence $presence): self
    {
        if (!$this->presence->contains($presence)) {
            $this->presence[] = $presence;
            $presence->setEmploye($this);
        }

        return $this;
    }

    public function removePresence(Presence $presence): self
    {
        if ($this->presence->removeElement($presence)) {
            // set the owning side to null (unless already changed)
            if ($presence->getEmploye() === $this) {
                $presence->setEmploye(null);
            }
        }

        return $this;
    }

    public function getPoste(): ?Poste
    {
        return $this->poste;
    }

    public function setPoste(?Poste $poste): self
    {
        $this->poste = $poste;

        return $this;
    }

}

templates/comptable/bulletinEmploye.html.twig
{% extends 'base.html.twig' %}
{% block title %}Bulletins de paie de {{ Employe.nom }} {{ Employe.prenom }}{% endblock %}
{% block stylesheets %}
    <style>
        .color-99CC5B{background-color:#00008B;}
        .color-99CC5B:hover{background-color:#00008B; }
        body {
            background-image: url('{{asset('/images/back.png')}}');
            background-repeat: repeat;
            margin: 0;
            padding: 0;
            background-color: white;
            height: 100vh;
        }
    </style>
{% endblock %}

{% block body %}
    <h1 style="color:#40A497"><strong><i>Bulletins de paie de {{ Employe.nom }} {{ Employe.prenom }}</i></strong></h1>
    <br>
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Total heures supp</th>
            <th scope="col">Total heures abs</th>
            <th scope="col">IEP</th>
            <th scope="col">Alloc fam</th>
            <th scope="col">Prime panier</th>
            <th scope="col">Cotisations</th>
            <th scope="col">Impots</th>
            <th scope="col">Total</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for Bulletin in Bulletin %}
            <tr>
                <td>{{ Bulletin.date|date('m-Y')}}</td>
                <td>{{ Bulletin.TotalHeureSupp}} heures</td>
                <td>{{ Bulletin.TotalHeureAbs}} heures</td>
                <td>+ {{ Bulletin.IEP|number_format(0,' ',' ') }} DA</td>
                <td>+ {{ Bulletin.allocationFamiliale|number_format(0,' ',' ') }} DA</td>
                <td>+ {{ Bulletin.panier|number_format(0,' ',' ') }} DA</td>
                <td>- {{ Bulletin.cotisations|number_format(0,' ',' ') }} DA</td>
                <td>- {{ Bulletin.impots|number_format(0,' ',' ') }} DA</td>
                <td>{{ Bulletin.total|number_format(0,' ',' ') }} DA</td>
                <td>
                    <a target="_blank" href="{{ path('comptable_fiche_paie',{id_bulletin:Bulletin.id})}}" class="btn btn-dark color-99CC5B">Afficher</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{{ path('comptable_profile_employe',{id:Employe.id})}}" class="btn btn-dark color-99CC5B">Retour</a>
{% endblock %}

templates/comptable/calculEffectue.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <style>
        .color-99CC5B{background-color:#00008B;}
        .color-99CC5B:hover{background-color:#00008B; }
        body {
            background-image: url('{{asset('/images/back.png')}}');
            background-repeat: repeat;
            margin: 0;
            padding: 0;
            background-color: white;
            height: 100vh;
        }
    </style>
{% endblock %}
{% block title %}Bulletins déjà calculés{% endblock %}

{% block body %}
    <br>
    <br>
    <hr style="color: #5c70d6">
    <h1 style="color:red"> <strong> <i> Les bulletins de ce mois ont déjà été calculés </i> </strong> <h1>
    <hr>
    <br>
    <br>
    <a href="{{ path('comptable',{date:rochdi})}}" class="btn btn-dark color-99CC5B"> Retour</a>
{% endblock %}

templates/comptable/calculPaie.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <style>
        .color-99CC5B{background-color:#00008B;}
        .color-99CC5B:hover{background-color:#00008B; }
        body {
            background-image: url('{{asset('/images/back.png')}}');
            background-repeat: repeat;
            margin: 0;
            padding: 0;
            background-color: white;
            height: 100vh;
        }
    </style>
{% endblock %}
{% block title %}Bulletins déjà calculés{% endblock %}

{% block body %}
    <br>
    <br>
    <hr style="color: #5c70d6">
    <h1 style="color:#40A497"><strong><i>Tous les bulletins de paie ont été calculés avec succès </i></strong></h1>
    <hr>
    <br>
    <br>
    <a href="{{ path('comptable',{date:rochdi})}}" class="btn btn-dark color-99CC5B"> Retour </a>
{% endblock %}

templates/comptable/confirmerOublie.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <style>
        .color-99CC5B{background-color:#00008B;}
        .color-99CC5B:hover{background-color:#00008B; }
        body {
            background-image: url('{{asset('/images/back.png')}}');
            background-repeat: repeat;
            margin: 0;
            padding: 0;
            background-color: white;
            height: 100vh;
        }
    </style>
{% endblock %}
{% block title %}Bulletins déjà calculés{% endblock %}

{% block body %}
    <br>
    <br>
    <hr style="color: #5c70d6">
    <h1 style="color:#40A497"><strong><i>Vous allez lancer le calcul des bulletins de paie du {{ date|date('m-Y') }} pour tous les employés </i></strong></h1>
    <hr>
    <a href="{{ path('calculPaie',{datecalcu:date})}}" class="btn btn-dark color-99CC5B"> Confirmer </a>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <a href="{{ path('comptable_paie_oublie',{date:date})}}" class="btn btn-dark color-99CC5B"> Retour </a>
{% endblock %}

templates/comptable/fiche_de_paie.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Fiche de paie</title>

    <style  type="text/css">
        body {
            background: #f0f0f0;
            display: flex;
            justify-content: center;
            padding: 20px;
            height: 100%;
            width: 100%;
        }
        @import url('https://fonts.googleapis.com/css?family=Roboto:200,300,400,600,700');

        * {
            font-family: 'Roboto', sans-serif;
            font-size: 12px;
            color: #444;
        }
        div#payslip {
            cursor: pointer;
            background: #fff;
            padding: 30px 40px;
        }

        div#title {
            font-size: 38px;
            font-weight: 600;
        }

        div#scope {
            margin-top: 20px;
            border-top: 1px solid #ccc;
            padding: 7px 0 4px 0;
            display: flex;
            justify-content: space-around;
        }

        div#scope div.scope-entry {
            text-align: center;
        }

        div#scope div.scope-entry div.value {
            font-size: 14px;
            font-weight: 700;
        }

        div.content {
            display: flex;
            height: 473px;
        }

        div.content div.left-panel {
            border-top: 1px solid #ccc;
            min-width: 200px;
            padding: 20px 16px 0 0;
            border-bottom: 1px solid #ccc;
        }

        div.content div.second-panel {
            border-top: 1px solid #ccc;
            border-left: 1px solid #ccc;
            width: 100%;
            padding: 10px 0  0 16px;
            border-bottom: 1px solid #ccc;
        }

        div#employee {
            text-align: center;
        }
        div#employee  div#name {
            font-size: 15px;
            font-weight: 700;
        }

        div#employee  div#email {
            font-size: 11px;
            font-weight: 300;
        }

        div.details, div.ytd {
            margin-top: 20px;
        }

        div.details div.entry, div.contributions div.entry, div.ytd div.entry {
            display: flex;
            justify-content: space-between;
            margin-top: 6px;
        }

        div.details div.entry div.value, div.contributions div.entry div.value, div.ytd div.entry div.value {
            font-weight: 700;
            max-width: 130px;
            text-align: end;
        }

        div.gross div.entry div.value {
            font-weight: 700;
            text-align: end;
            font-size: 16px;
        }

        div.contributions div.title, div.ytd div.title, div.gross div.title {
            font-size: 15px;
            font-weight: 700;
            border-bottom: 1px solid #ccc;
            padding: 4px;
            margin: 6px;
        }

        div.content div.second-panel div.details {
            width: 100%;
        }

        div.content div.second-panel div.details div.entry {
            display: flex;
            padding: 0 10px;
            margin: 6px 0;
        }

        div.content div.second-panel div.details div.label {
            font-weight: 700;
            width: 120px;
        }

        div.content div.second-panel div.details div.detail {
            font-weight: 600;
            width: 130px;
        }

        div.content div.second-panel div.details div.rate {
            font-weight: 400;
            width: 80px;
            font-style: italic;
            letter-spacing: 1px;
        }

        div.content div.second-panel div.details div.amount {
            text-align: end;
            font-weight: 700;
            width: 90px;
        }

        div.content div.second-panel div.details div.net_pay div, div.content div.second-panel div.details div.nti div {
            font-weight: 600;
            font-size: 12px;
        }

        div.content div.second-panel div.details div.net_pay {
            padding: 3px 0 2px 0;
            margin-top: 10px;
            background: rgba(0, 0, 0, 0.04);
        }
    </style>
</head>
<div id="payslip">
    <div id="title">Bulletin de paie</div>
    <div id="scope">
        <div class="scope-entry">
            <div class="title">PÉRIODE</div>
            <div class="value">{{ Bulletin.date|date('m-Y')}}</div>
        </div>
    </div>
    <div class="content">
        <div class="left-panel">
            <div id="employee">
                <div id="name">
                    {{ Employe.nom }} {{ Employe.prenom }}
                </div>
                <div id="email">
                    {{ Employe.email }}
                </div>
            </div>
            <div class="details">
                <div class="entry">
                    <div class="label">ID</div>
                    <div class="value">{{ Employe.id }}</div>
                </div>
                <div class="entry">
                    <div class="label">Sexe</div>
                    <div class="value">{{ Employe.sexe }}</div>
                </div>
                <div class="entry">
                    <div class="label">Situation familiale</div>
                    <div class="value">{{ Employe.situationFamiliale }}</div>
                </div>
                <div class="entry">
                    <div class="label">Nombre d'enfants</div>
                    <div class="value">{{ Employe.nombreEnfant }}</div>
                </div>
                <div class="entry">
                    <div class="label">Date de recrutement</div>
                    <div class="value">{{ dateRecrutement }}</div>
                </div>
                <div class="entry">
                    <div class="label">Poste</div>
                    <div class="value">{{ Employe.poste }}</div>
                </div>
                <div class="entry">
                    <div class="label">Filiale</div>
                    <div class="value">{{ Employe.filiale }}</div>
                </div>
                <div class="entry">
                    <div class="label">CCP</div>
                    <div class="value">{{ Employe.ccp }}</div>
                </div>
            </div>
            <div class="ytd">
                <div class="title">Informations poste</div>
                <div class="entry">
                    <div class="label">Salaire par heure</div>
                    <div class="value">{{ salaireParHeure|number_format(0,'.','.') }} DA</div>
                </div>
                <div class="entry">
                    <div class="label">Jours par semaine</div>
                    <div class="value">{{ Poste.NbJourSemaine }} jours</div>
                </div>
                <div class="entry">
                    <div class="label">Heures par jour</div>
                    <div class="value">{{ Poste.NbHeureJour }} heures</div>
                </div>
            </div>
            <div class="ytd">
                <div class="title">Presences / Absences</div>
                <div class="entry">
                    <div class="label">Heures absentées</div>
                    <div class="value">{{ Bulletin.TotalHeureAbs }}</div>
                </div>
                <div class="entry">
                    <div class="label">Heures supp</div>
                    <div class="value">{{  Bulletin.TotalHeureSupp }}</div>
                </div>
            </div>
        </div>
        <div class="second-panel">
            <div class="details">
                <div class="salary">
                    <div class="entry">
                        <div class="label"><strong>VERSEMENTS</strong></div>
                        <div class="detail"></div>
                        <div class="rate"></div>
                        <div class="amount"></div>
                    </div>
                    <div class="entry">
                        <div class="label"></div>
                        <div class="detail">Salaire de base</div>
                        <div class="amount">{{ Poste.SalaireDeBase|number_format(0,' ',' ') }} DA</div>
                    </div>
                    <div class="entry">
                        <div class="label"></div>
                        <div class="detail">Montant heures supp</div>
                        <div class="amount">{{ montantHeureSupp|number_format(0,' ',' ') }} DA</div>
                    </div>
                    <div class="entry">
                        <div class="label"></div>
                        <div class="detail">IEP (Prime d'ancienneté)</div>
                        <div class="amount">{{ Bulletin.iep|number_format(0,' ',' ') }} DA</div>
                    </div>
                    <div class="entry">
                        <div class="label"></div>
                        <div class="detail">Allocation familiale</div>
                        <div class="amount">{{ Bulletin.allocationFamiliale|number_format(0,' ',' ') }} DA</div>
                    </div>
                    <div class="entry">
                        <div class="label"></div>
                        <div class="detail">Prime de panier</div>
                        <div class="amount">{{ Bulletin.panier|number_format(0,' ',' ') }} DA</div>
                    </div>
                </div>
                <div class="leaves">
                    <div class="entry">
                        <div class="label"><strong>RETENUES</strong></div>
                        <div class="detail"></div>
                        <div class="rate"></div>
                        <div class="amount"></div>
                    </div>
                    <div class="entry paid">
                        <div class="label"></div>
                        <div class="detail">Montant heures absentées</div>
                        <div class="amount">{{ montantHeureAbs|number_format(0,' ',' ') }} DA</div>
                    </div>
                    <div class="entry unpaid">
                        <div class="label"></div>
                        <div class="detail">Cotisations</div>
                        <div class="amount">{{ Bulletin.cotisations|number_format(0,' ',' ') }} DA</div>
                    </div>
                    <div class="entry unpaid">
                        <div class="label"></div>
                        <div class="detail">Impots</div>
                        <div class="amount">{{ Bulletin.impots|number_format(0,' ',' ') }} DA</div>
                    </div>
                </div>
                <div class="net_pay">
                    <div class="entry">
                        <div class="label"><strong>NET A PAYER</strong></div>
                        <div class="detail"></div>
                        <div class="rate"></div>
                        <div class="amount">{{ Bulletin.total|number_format(0,' ',' ') }} DA</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById("payslip").addEventListener("dblclick", myFunction);

    function myFunction() {
        window.print();
    }
</script>
</html>

templates/comptable/historiquePresence.html.twig
{% extends 'base.html.twig' %}
{% block title %}Mon historique de présence{% endblock %}
{% block stylesheets %}
    <style>
        .color-99CC5B{background-color:#00008B;}
        .color-99CC5B:hover{background-color:#00008B; }
        body {
            background-image: url('{{asset('/images/back.png')}}');
            margin: 0;
            padding: 0;
            background-color: white;
            height: 100vh;
        }
    </style>
{% endblock %}
{% block body %}
    <h1 style="color:#40A497"><strong><i>Mon historique de présence</i></strong></h1>
    <br>
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Heure d'arrivee</th>
            <th scope="col">Heure de sortie</th>
        </tr>
        </thead>
        <tbody>
        {% for Presence in Presence %}
            <tr>
                <td>{{ Presence.date.format('Y-m-d')}}</td>
                <td>{{ Presence.HeureIn.format('H:m')}}</td>
                <td>{{ Presence.HeureOut.format('H:m')}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('comptable',{date:date})}}" class="btn btn-dark color-99CC5B">Retour</a>
{% endblock %}

templates/comptable/probleme.html.twig
{% extends 'probleme.html.twig' %}
{% block retour %}
    <a href="{{ path('comptable',{date:date}) }}" class="btn btn-dark color-99CC5B">Retour</a>
{% endblock %}

templates/comptable/probleme_envoye.html.twig
{% extends 'probleme_envoye.html.twig' %}
    {% block retour %}
        <a href="{{ path('comptable',{date:date})}}" class="btn btn-dark color-99CC5B"> Retour </a>
    {% endblock %}

templates/comptable/viewBulletin.html.twig
{% extends 'base.html.twig' %}
{% block title %}Mes bulletins{% endblock %}
{% block stylesheets %}
    <style>
        .color-99CC5B{background-color:#00008B;}
        .color-99CC5B:hover{background-color:#00008B; }
        body {
            background-image: url('{{asset('/images/back.png')}}');
            margin: 0;
            padding: 0;
            background-color: white;
            height: 100vh;
        }
    </style>
{% endblock %}

{% block body %}
    <h1 style="color:#40A497"><strong><i>Mes bulletins de paie</i></strong></h1>
    <br>
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Total heures supp</th>
            <th scope="col">Total heures abs</th>
            <th scope="col">IEP</th>
            <th scope="col">Alloc fam</th>
            <th scope="col">Prime panier</th>
            <th scope="col">Cotisations</th>
            <th scope="col">Impots</th>
            <th scope="col">Total</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for Bulletin in Bulletin %}
            <tr>
                <td>{{ Bulletin.date|date('m-Y')}}</td>
                <td>{{ Bulletin.TotalHeureSupp}} heures</td>
                <td>{{ Bulletin.TotalHeureAbs}} heures</td>
                <td>+ {{ Bulletin.IEP|number_format(0,' ',' ') }} DA</td>
                <td>+ {{ Bulletin.allocationFamiliale|number_format(0,' ',' ') }} DA</td>
                <td>+ {{ Bulletin.panier|number_format(0,' ',' ') }} DA</td>
                <td>- {{ Bulletin.cotisations|number_format(0,' ',' ') }} DA</td>
                <td>- {{ Bulletin.impots|number_format(0,' ',' ') }} DA</td>
                <td>{{ Bulletin.total|number_format(0,' ',' ') }} DA</td>
                <td>
                    <a target="_blank" href="{{ path('comptable_fiche_paie',{id_bulletin:Bulletin.id})}}" class="btn btn-dark color-99CC5B">Afficher</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{{ path('comptable',{date:date})}}" class="btn btn-dark color-99CC5B">Retour</a><br>
{% endblock %}